name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tox
    - name: Run tests
      run: tox

  scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Run Aegis Scanner
      run: docker run --rm -v ${{ github.workspace }}:/workspace pegasysai/aegis-scanner:latest --token ${{ secrets.AEGIS_TOKEN }} --workspace '/workspace'

  build:
    runs-on: ubuntu-latest
    needs: scan
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t flask-app .
